import 'dart:ui';

class Translator {
  static const Map<String, Map<String, String>> _localizedStrings = {
    'en-US': {
      'order_date': 'Order Date',
      'table_no': 'Table No',
      'long_id': 'Long ID',
      'branch_name': 'Branch Name',
      'note_to_customer': '**Note to customer: check order receipt in delivery app for final price**',
      'order_status': 'Order Status',
      'x_item': 'X item',
      'subtotal': 'Subtotal',
      'inc_vat': 'Inc. Vat',
      'restaurant_service_fee': 'Restaurant Service Fee',
      'total': 'Total',
      'internal_id': 'INTERNAL ID',
      'powered_by': 'Powered By',
      'queue_no': 'Queue No',
      'generated_date': 'Generated Date',
      'sales_summary': 'Sales Summary',
      'total_sales': 'Total Sales',
      'discount': 'Discount',
      'net_sales': 'Net Sales',
      'brand_summary': 'Brand Summary',
      'item_summary': 'Item Summary',
      'item': 'Item',
      'quantity': 'Quantity',
      'modifier_summary': 'Modifier Summary',
      'payment_method_summary': 'Payment Method Summary',
      'payment_method': 'Payment Method',
      'amount': 'Amount',
      'total_amount': 'Total',
      'net_amount': 'Net',
      'payment_channel_summary': 'Payment Channel Summary',
      'payment_channel': 'Payment Channel',
      'modifier': 'Modifier',
      'z_report': 'Z-Report',
      'qty': 'Qty',
      'customer_name': 'Customer Name',
      'estimated_pickup_time': 'Estimated Pickup Time',
      'note': 'Note',
      'at': 'at',
      'delivery_fee': 'Delivery Fee',
      'additional_fee': 'Additional Fee',
      'service_fee': 'Service Fee',
      'processing_fee': 'Processing Fee',
      'reward': 'Reward',
      'rounding_off': 'Rounding Off',
      'pickup_time': 'PickUp Time',
      'driver_name': 'Driver Name',
      'driver_phone': 'Driver Phone',
      'license_plate': 'License Plate',
      'vat': 'Vat',
      'items': 'Items',
      'price': 'Price',
      'x_item_s': 'item(s)',
      'delivery_address': 'Delivery Address',
      'delivery_time': 'Delivery Time',
      'payment_status': 'Payment Status',
    },
    'id-ID': {
      'order_date': 'Tanggal Pesanan',
      'table_no': 'No Meja',
      'long_id': 'Long ID',
      'branch_name': 'Nama Cabang',
      'note_to_customer': '**Catatan untuk kustomer: periksa struk pesanan di aplikasi untuk harga total**',
      'order_status': 'Status Pesanan',
      'x_item': 'Item X',
      'subtotal': 'Subtotal',
      'inc_vat': 'Pajak Inc',
      'restaurant_service_fee': 'Biaya Layanan',
      'total': 'Total',
      'internal_id': 'INTERNAL ID',
      'powered_by': 'Powered By',
      'queue_no': 'No Antrian',
      'generated_date': 'Tanggal Dicetak',
      'sales_summary': 'Rekap Penjualan',
      'total_sales': 'Total Penjualan',
      'discount': 'Diskon',
      'net_sales': 'Penjualan Bersih',
      'brand_summary': 'Rekap Brand',
      'item_summary': 'Rekap Item',
      'item': 'Item',
      'quantity': 'Kuantitas',
      'modifier_summary': 'Rekap Modifier',
      'payment_method_summary': 'Rekap Metode Pembayaran',
      'payment_method': 'Metode Pembayaran',
      'amount': 'Jumlah',
      'total_amount': 'Total',
      'net_amount': 'Net',
      'payment_channel_summary': 'Rekap Channel Pembayaran',
      'payment_channel': 'Channel Pembayaran',
      'modifier': 'Modifier',
      'z_report': 'Z-Report',
      'qty': 'Jumlah',
      'customer_name': 'Nama Pelanggan',
      'estimated_pickup_time': 'Waktu Pengambilan yang Diperkirakan',
      'x_item_s': 'X item(s)',
      'delivery_address': 'Alamat Pengiriman',
      'note': 'Catatan',
      'at': 'pada',
      'delivery_fee': 'Biaya Pengiriman',
      'additional_fee': 'Biaya Tambahan',
      'service_fee': 'Biaya Layanan',
      'processing_fee': 'Biaya Pengolahan',
      'reward': 'Penghargaan',
      'rounding_off': 'Pembulatan',
      'pickup_time': 'Waktu Pengambilan',
      'driver_name': 'Nama Pengemudi',
      'driver_phone': 'Telepon Pengemudi',
      'license_plate': 'Plat Nomor Kendaraan',
      'vat': 'Pajak',
      'items': 'Barang-barang',
      'price': 'Harga',
      'delivery_time': 'Waktu Pengiriman',
      'payment_status': 'Status pembayaran',
    },
    'zh-CHS': {
      'order_date': '订单日期',
      'table_no': '桌号',
      'long_id': '长ID',
      'branch_name': '分行名称',
      'note_to_customer': '**顾客注意：请在送货应用中查看订单收据以获取最终价格**',
      'order_status': '订单状态',
      'x_item': 'X 项目',
      'subtotal': '小计',
      'inc_vat': '含增值税',
      'restaurant_service_fee': '餐厅服务费',
      'total': '总计',
      'internal_id': '内部编号',
      'powered_by': '由...提供动力',
      'queue_no': '排队号码',
      'generated_date': '生成日期',
      'sales_summary': '销售总结',
      'total_sales': '总销售额',
      'discount': '折扣',
      'net_sales': '净销售额',
      'brand_summary': '品牌总结',
      'item_summary': '物品摘要',
      'item': '项目',
      'quantity': '数量',
      'modifier_summary': '修改者摘要',
      'payment_method_summary': '支付方式摘要',
      'payment_method': '支付方式',
      'amount': '金额',
      'total_amount': '总计',
      'net_amount': '网',
      'payment_channel_summary': '支付渠道总结',
      'payment_channel': '支付渠道',
      'modifier': '修饰词',
      'z_report': 'Z-报告',
      'qty': '数量',
      'customer_name': '顾客姓名',
      'estimated_pickup_time': '预计取货时间',
      'x_item_s': 'X 个项目',
      'delivery_address': '送货地址',
      'note': '注意',
      'at': '在',
      'delivery_fee': '配送费',
      'additional_fee': '额外费用',
      'service_fee': '服务费',
      'processing_fee': '处理费',
      'reward': '奖励',
      'rounding_off': '四舍五入',
      'pickup_time': '取货时间',
      'driver_name': '司机姓名',
      'driver_phone': '司机电话',
      'license_plate': '车牌',
      'vat': '增值税',
      'items': '物品',
      'price': '价格',
      'delivery_time': '交货时间',
      'payment_status': '支付状态',
    },
    'zh-TW': {
      'order_date': '訂單日期',
      'table_no': '桌號',
      'long_id': 'ID',
      'branch_name': '分店名稱',
      'note_to_customer': '請注意：請在您的外送APP內查看訂單資訊以獲得最終價格',
      'order_status': '訂單狀態',
      'x_item': 'X項目',
      'subtotal': '小計',
      'inc_vat': '含稅',
      'restaurant_service_fee': '餐廳服務費',
      'total': '總額',
      'internal_id': '內部ID',
      'powered_by': 'Powered By',
      'queue_no': '排隊號碼',
      'generated_date': '生成日期',
      'sales_summary': '銷售摘要',
      'total_sales': '總銷售額',
      'discount': '折扣',
      'net_sales': '淨銷售額',
      'brand_summary': '品牌摘要',
      'item_summary': '物品摘要',
      'item': '項目',
      'quantity': '數量',
      'modifier_summary': '客製化品項摘要',
      'payment_method_summary': '付款方式摘要',
      'payment_method': '付款方式',
      'amount': '金額',
      'total_amount': '總計',
      'net_amount': '網絡',
      'payment_channel_summary': '付款渠道摘要',
      'payment_channel': '付款通道',
      'modifier': '客製化品項',
      'z_report': '每日報告',
      'customer_name': '客戶姓名',
      'estimated_pickup_time': '預計取件時間',
      'x_item_s': '「X件商品」',
      'delivery_address': '送貨地址',
      'note': '注意',
      'delivery_fee': '運費',
      'additional_fee': '額外費用',
      'service_fee': '服務費',
      'processing_fee': '處理費',
      'reward': '獎勵',
      'rounding_off': '四捨五入',
      'pickup_time': '取貨時間',
      'driver_name': '司機姓名',
      'driver_phone': '司機手機',
      'license_plate': '車牌',
      'vat': '增值稅',
      'items': '項目',
      'price': '價格',
      'qty': '數量',
      'at': '在',
      'delivery_time': '外送時間',
      'payment_status': '付款狀態',
    },
    'th-TH': {
      'order_date': 'วันที่ออเดอร์',
      'table_no': 'หมายเลขโต๊ะ',
      'long_id': 'ID',
      'branch_name': 'ชื่อสาขา',
      'note_to_customer': '**หมายเหตุถึงลูกค้า: ตรวจสอบใบเสร็จรับเงินในแอป Delivery เพื่อดูราคาสุดท้าย**',
      'order_status': 'สถานะการสั่งซื้อ',
      'x_item': 'รายการ X',
      'subtotal': 'ผลรวมย่อย',
      'inc_vat': 'รวม Vat',
      'restaurant_service_fee': 'ค่าบริการร้านอาหาร',
      'total': 'ทั้งหมด',
      'internal_id': 'รหัสภายใน',
      'powered_by': 'ขับเคลื่อนโดย',
      'queue_no': 'หมายเลขคิว',
      'generated_date': 'วันที่สร้าง',
      'sales_summary': 'สรุปการขาย',
      'total_sales': 'ยอดขายทั้งหมด',
      'discount': 'การลดราคา',
      'net_sales': 'ราคาขายสุทธิ',
      'brand_summary': 'สรุปแบรนด์',
      'item_summary': 'สรุปรายการ',
      'item': 'รายการ',
      'quantity': 'ปริมาณ',
      'modifier_summary': 'สรุปตัวเลือก',
      'payment_method_summary': 'สรุปวิธีการชำระเงิน',
      'payment_method': 'วิธีการชำระเงิน',
      'amount': 'จำนวน',
      'total_amount': 'ทั้งหมด',
      'net_amount': 'สุทธิ',
      'payment_channel_summary': 'สรุปช่องทางการชำระเงิน',
      'payment_channel': 'ช่องทางการชำระเงิน',
      'modifier': 'ตัวเลือก',
      'z_report': 'รายงาน Z-Report',
      'qty': 'จำนวน',
      'at': 'ที่',
      'customer_name': 'ชื่อลูกค้า',
      'estimated_pickup_time': 'เวลาที่คาดว่าจะมารับ',
      'x_item_s': 'X รายการ',
      'delivery_address': 'ที่อยู่สำหรับการจัดส่ง',
      'note': 'หมายเหตุ',
      'delivery_fee': 'ค่าจัดส่ง',
      'additional_fee': 'ค่าธรรมเนียมเพิ่มเติม',
      'service_fee': 'ค่าบริการ',
      'processing_fee': 'ค่าธรรมเนียมการประมวลผล',
      'reward': 'รางวัล',
      'rounding_off': 'การปัดเศษ',
      'pickup_time': 'เวลารับสินค้า',
      'driver_name': 'ชื่อคนขับ',
      'driver_phone': 'โทรศัพท์ของคนขับ',
      'license_plate': 'แผ่นป้ายทะเบียน',
      'vat': 'ภาษีมูลค่าเพิ่ม',
      'items': 'รายการสินค้า',
      'price': 'ราคา',
      'delivery_time': 'เวลาการจัดส่ง',
      'payment_status': 'สถานะการชำระเงิน',
    },
    'ja-JP': {
      'order_date': '注文日',
      'table_no': 'テーブル番号',
      'long_id': 'ID',
      'branch_name': '店舗名',
      'note_to_customer': 'お客様へ、アプリから詳細をご確認ください',
      'order_status': '注文状況',
      'x_item': 'X商品',
      'subtotal': '小計',
      'inc_vat': '消費税込み',
      'restaurant_service_fee': 'レストラン手数料',
      'total': '合計',
      'internal_id': 'klikit ID',
      'powered_by': 'Powered by',
      'queue_no': '注文番号',
      'generated_date': '生成日',
      'sales_summary': '売り上げ概要',
      'total_sales': '売り上げ',
      'discount': '割引',
      'net_sales': '営業利益',
      'brand_summary': 'ブランド概要',
      'item_summary': '商品概要',
      'item': '商品',
      'quantity': '個数',
      'modifier_summary': 'アドオン概要',
      'payment_method_summary': '支払い方法概要',
      'payment_method': '支払い方法',
      'amount': '小計',
      'total_amount': '合計',
      'net_amount': '営業利益',
      'payment_channel_summary': 'ペイメントゲートウェイ概要',
      'payment_channel': 'ペイメントゲートウェイ',
      'modifier': 'アドオン',
      'z_report': '1日のレポート',
      'qty': '量',
      'at': 'で',
      'customer_name': '「顧客名」',
      'estimated_pickup_time': '「おおよその受け取り時間」',
      'x_item_s': '個のアイテム',
      'delivery_address': '配送先住所',
      'note': '「注意」',
      'delivery_fee': '「配送料」',
      'additional_fee': '「追加料金」',
      'service_fee': '「サービス料金」',
      'processing_fee': '手数料 (tesuryou)',
      'reward': '報酬',
      'rounding_off': '「四捨五入」',
      'pickup_time': '「ピックアップの時間」',
      'driver_name': '「ドライバー名」',
      'driver_phone': '「ドライバーの携帯電話」',
      'license_plate': 'ナンバープレート',
      'vat': '「消費税」',
      'items': '「アイテム」',
      'price': '価格',
      'delivery_time': '配達時間',
      'payment_status': 'お支払い状況',
    }
  };
  static Locale _userLocale = const Locale('en', 'US');

  static void setLocale(Locale locale) {
    _userLocale = locale;
  }

  static Locale getLocale() {
    return _userLocale;
  }

  static String translate(String key) {
    return _localizedStrings['${_userLocale.languageCode}-${_userLocale.countryCode}']?[key] ?? key;
  }
}
